import { TWordExample } from "./types";

export const wordDB: TWordExample[] = [
  {
    word: 'СОК',
    level: 1,
    id: 'sok',
    alt: 'Сок',
    url: '/word-img/sok.png',
  },
  {
    word: 'ЛУК',
    level: 1,
    id: 'luk',
    alt: 'Лук',
    url: 'word-img/luk.png',
  },
  {
    word: 'СТОЛ',
    level: 2,
    id: 'stol',
    alt: 'Стол',
    url: '/word-img/table.png',
  },
  {
    word: 'СЛОН',
    level: 2,
    id: 'slon',
    alt: 'Слон',
    url: '/word-img/elephant.png',
  },
  {
    word: 'ДОМ',
    level: 1,
    id: 'dom',
    alt: 'Дом',
    url: '/word-img/house.png',
  },
  {
    word: 'КОТ',
    level: 1,
    id: 'kot',
    alt: 'Кот',
    url: '/word-img/cat.png',
  },
  {
    word: 'ПОЛ',
    level: 1,
    id: 'pol',
    alt: 'Пол',
    url: '/word-img/floor.png',
  },
  {
    word: 'МАТ',
    level: 1,
    id: 'mat',
    alt: 'Мат',
    url: '/word-img/mat.png',
  },
  {
    word: 'БАЛ',
    level: 1,
    id: 'bal',
    alt: 'Бал',
    url: '/word-img/bal.png',
  },
  {
    word: 'БОТ',
    level: 1,
    id: 'bot',
    alt: 'Бот',
    url: '/word-img/bot.png',
  },
  {
    word: 'ВАТА',
    level: 1,
    id: 'vata',
    alt: 'Вата',
    url: '/word-img/cotton.png',
  },
];